export const DEFAULT_DECIMALS = 18
export const PRICE_DECIMALS = 18
export const AAVE_ORACLE_DECIMALS = 8
export const APY_RAY_DECIMALS = 27
export const EULER_FEE_SCALE = 10_000
export const ISOLATED_LTV_PRECISION = 1e5
export const ISOLATED_RATE_PRECISION = 1e18
export const PERFORMANCE_FEE_PRECISION = 1e18
export const LTV_BPS_DIVISOR = 100

export const HEALTH_FACTOR_RISK_THRESHOLD = 1.5